# Generated by Django 2.2.3 on 2019-07-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BixiStationOccupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('station_id', models.IntegerField()),
                ('short_name', models.CharField(max_length=5)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('occupation', models.IntegerField()),
                ('year', models.IntegerField()),
                ('day', models.CharField(choices=[('W-SUN', 'Sunday'), ('W-MON', 'Monday'), ('W-TUE', 'Tuesday'), ('W-WED', 'Wednesday'), ('W-THU', 'Thursday'), ('W-FRI', 'Friday'), ('W-SAT', 'Saturday')], default='W-SUN', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
